Source: SerenityTpg
BoardId: SerenityU
Timestamp: 1750076666
TpgControl:
  SelfTriggerDelay: 407
  NumberOfLpGbtPairs: 2
  LpGbtPair:
    - UnpackerBlock:
        BxLatency: 0
        Stc4AUnpackerDelay: 3
        Stc16UnpackerDelay: 3
        NumberOfUnpackers: 4
        Unpackers:
          - Type: 1
          - Type: 1
          - Type: 1
          - Type: 1
      SelfTrigger:
        NumberOfEconts: 6
        Econt:
          - EcontThreshold: 511
            TcEnableBits: 16383
            EcontEnable: 0
          - EcontThreshold: 511
            TcEnableBits: 16383
            EcontEnable: 0
          - EcontThreshold: 511
            TcEnableBits: 16383
            EcontEnable: 0
          - EcontThreshold: 511
            TcEnableBits: 16383
            EcontEnable: 0
          - EcontThreshold: 511
            TcEnableBits: 16383
            EcontEnable: 0
          - EcontThreshold: 511
            TcEnableBits: 16383
            EcontEnable: 0
    - UnpackerBlock:
        BxLatency: 0
        Stc4AUnpackerDelay: 3
        Stc16UnpackerDelay: 3
        NumberOfUnpackers: 6
        Unpackers:
          - Type: 0
          - Type: 0
          - Type: 0
          - Type: 2
          - Type: 2
          - Type: 2
      SelfTrigger:
        NumberOfEconts: 6
        Econt:
          - EcontThreshold: 511
            TcEnableBits: 16383
            EcontEnable: 0
          - EcontThreshold: 511
            TcEnableBits: 16383
            EcontEnable: 0
          - EcontThreshold: 511
            TcEnableBits: 16383
            EcontEnable: 0
          - EcontThreshold: 511
            TcEnableBits: 16383
            EcontEnable: 0
          - EcontThreshold: 511
            TcEnableBits: 16383
            EcontEnable: 0
          - EcontThreshold: 511
            TcEnableBits: 16383
            EcontEnable: 0
TpgReadout:
  BackpressureDisable: 0
  NumberOfChannels: 14
  Channel:
    - Latency: 11
      TmuxId: 0
      ReadoutWindow: 0
      WordsPerBx: 8
      Masked: 0
    - Latency: 1617
      TmuxId: 0
      ReadoutWindow: 3
      WordsPerBx: 4
      Masked: 0
    - Latency: 1629
      TmuxId: 0
      ReadoutWindow: 3
      WordsPerBx: 4
      Masked: 0
    - Latency: 1629
      TmuxId: 0
      ReadoutWindow: 3
      WordsPerBx: 4
      Masked: 0
    - Latency: 1636
      TmuxId: 0
      ReadoutWindow: 3
      WordsPerBx: 4
      Masked: 0
    - Latency: 3219
      TmuxId: 0
      ReadoutWindow: 3
      WordsPerBx: 8
      Masked: 0
    - Latency: 3217
      TmuxId: 0
      ReadoutWindow: 3
      WordsPerBx: 8
      Masked: 0
    - Latency: 3217
      TmuxId: 0
      ReadoutWindow: 3
      WordsPerBx: 8
      Masked: 0
    - Latency: 3225
      TmuxId: 0
      ReadoutWindow: 3
      WordsPerBx: 8
      Masked: 0
    - Latency: 2985
      TmuxId: 0
      ReadoutWindow: 3
      WordsPerBx: 7
      Masked: 0
    - Latency: 3200
      TmuxId: 0
      ReadoutWindow: 3
      WordsPerBx: 8
      Masked: 0
    - Latency: 3200
      TmuxId: 0
      ReadoutWindow: 3
      WordsPerBx: 8
      Masked: 0
    - Latency: 3200
      TmuxId: 0
      ReadoutWindow: 3
      WordsPerBx: 8
      Masked: 0
    - Latency: 3200
      TmuxId: 0
      ReadoutWindow: 3
      WordsPerBx: 8
      Masked: 0
TpgFastControl:
  L1aStretch: 0
  SlinkFifoOffset: 0
  EnableSlinkFifoThrottle: 1
